//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.18 at 11:48:15 PM BOT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://emi.bo/estudiantes", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bo.emi.envelopes.envelopes;
